title: Scrape With Yuri
description: Web Scraping Tutorials and Walkthroughs using Python and VBA
author: Yuri Douglas
github: https://github.com/ScrapeWithYuri
about: I am a programmer and a CPA accountant. My primary focus is on large-scale, efficient web scraping using Python, Scrapy, Selenium and VBA.
disqus_shortname: ScrapeWithYuri
google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/yuri-douglas-cpa-293921a5"
    - icon: fa-github
      link: "https://github.com/ScrapeWithYuri"

share:
  twitter_username: github.io
  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://scrapewithyuri.github.io"
baseurl: "/blog/"
paginate: 10
per_page: 10
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
